### ISSUE TITLE
Use with Azure self-hosted agent in Docker

### ISSUE THREAD

**Issue by bdovaz** [slonopotamus/stevedore#68]
### Stevedore Version

2.3.0

### What steps are needed to reproduce the behavior?

I have tried to set up two agents on the same Windows 11 Pro machine by installing Docker with **stevedore**:

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#windows

### What you expected?

It should work.

### What happened?

I have strange I/O errors like access denied on file copies or files in use by the **vmwp.exe** process.

**This same Azure pipeline works perfectly on self-hosted Windows agents that are not on Docker but installed in the host machine itself.**

ERROR 1

The process cannot access the file '{MY_FILE}' because it is being used by another process.

ERROR 2

git clean errors that came from files in use by the **vmwp.exe** process (I don't know why):

warning: failed to remove {MY_FILE}: Invalid argument

ERROR 3

[DownloadSingleArtifactAsync] Try 1/3, retryable exception caught. Retrying in 00:00:01. System.UnauthorizedAccessException: Access denied: {MY_FILE}
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadAndHardlinkTempFile(DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadToFileAsync(DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupIdentifier dedupId, String fullPath, UInt64 fileSize, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.<>c__DisplayClass31_0.<<DownloadAsyncWithManifestPath>b__5>d.MoveNext()

**Comment by slonopotamus** [comment]
No idea what's going on here and do not have access to Azure. PRs fixing the issue are welcomd though.
